/*
* Generated file
*
* Generated from: yang module name: registryhandler-impl yang module local name: registryhandler-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sun Nov 05 09:54:07 CET 2017
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.neonsh.registryhandler.impl;
public class RegistryHandlerModuleFactory extends eu.neonsh.registryhandler.impl.AbstractRegistryHandlerModuleFactory {

}
