/*
* Generated file
*
* Generated from: yang module name: nshmanager-impl yang module local name: nshmanager-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sun Nov 05 10:08:57 CET 2017
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.neonsh.nshmanager.impl;
public class NSHManagerModuleFactory extends eu.neonsh.nshmanager.impl.AbstractNSHManagerModuleFactory {

}
